Add install commands and __init__.py
luator/boost_python_catkin_example pull request #2
Opened 2017-04-07 08:47 UTC by mehditlili

After installing my package, I noticed that an __init__.py was missing and python was unable to import correctly.

2017-04-08 06:40 UTC, luator requested changes
Thanks for your input, it is very appreciated!

I have some comments on the installation of the python script (see below).
And a question to the `__init__.py` file: Is this really necessary for some reason? If not, I would prefer to remove it to keep this example as minimal as possible (i.e. only including parts that are necessary for getting the Boost Python bindings to work).

2017-04-08 06:40 UTC, luator commented on CMakeLists.txt
> +file(GLOB py_files "scripts/*.py")
To keep it minimalist, I would prefer to not use the `file` command but just use the explicit filename.

2017-04-08 06:40 UTC, luator commented on CMakeLists.txt
> +install(PROGRAMS ${py_files}
Please use the `catkin_install_python` macro to install python scripts. See http://docs.ros.org/kinetic/api/catkin/html/howto/format2/installing_python.html

2017-04-12 13:10 UTC, mehditlili commented
When I tried without the __init__.py, the mycpplib.so is installed but can't be imported in Python.

2017-04-23 17:27 UTC, luator commented
Sorry for the late response, looks good now :). Thanks again.

2017-04-23 17:28 UTC, merged